## database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/permission?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

## mybatis
mybatis:
  mapper-locations: mappers/*.xml
#  mapper-locations: mappers/*.xml
  type-aliases-package: org.yangxin.permission.model
#  org.yangxin.permission.model
